optuna:
  study_name: 'listops32_transformer_hyperparam_opt'
  pruner:
    type: 'MedianPruner'
    n_warmup_steps: 5

listops32:
  data_processing:
    raw_train_data_path: data/raw/train-00000-of-00001.parquet
    raw_val_data_path: data/raw/validation-00000-of-00001.parquet
    raw_test_data_path: data/raw/test-00000-of-00001.parquet
    tk_train_data_path: data/processed/listops32_tk_train_X.parquet
    tk_train_label_path: data/processed/listops32_tk_train_y.parquet
    tk_val_data_path: data/processed/listops32_tk_val_X.parquet
    tk_val_label_path: data/processed/listops32_tk_val_y.parquet
    tk_test_data_path: data/processed/listops32_tk_test_X.parquet
    tk_test_label_path: data/processed/listops32_tk_test_y.parquet
    dictionary_path: data/processed/listops32_dictionary.json
  train_model:

models:
  base_transformer:

  energy_transformer: