all:
  project_name: 'listops32_nrgpt_baseTran'
  model_type: 'base_transformer'
  device: 'cuda'
  n_gpus: 2
  n_trials: 4
  wandb_config_file: 'wandb_config_no_model_params.yaml'
  optuna_config_file: 'optuna_config.yaml'

# TODO: refactor into separate file
optuna:
  study_name: 'listops32_transformer_hyperparam_opt'
  n_trials: 100
  pruner:
    type: 'MedianPruner'
    n_warmup_steps: 5

listops32:
  data_processing:
    raw_train_data_path: data/raw/train-00000-of-00001.parquet
    raw_val_data_path: data/raw/validation-00000-of-00001.parquet
    raw_test_data_path: data/raw/test-00000-of-00001.parquet
    tk_train_data_path: data/processed/listops32_tk_train_X.parquet
    tk_train_label_path: data/processed/listops32_tk_train_y.parquet
    tk_val_data_path: data/processed/listops32_tk_val_X.parquet
    tk_val_label_path: data/processed/listops32_tk_val_y.parquet
    tk_test_data_path: data/processed/listops32_tk_test_X.parquet
    tk_test_label_path: data/processed/listops32_tk_test_y.parquet
    dictionary_path: data/processed/listops32_dictionary.json
  # TODO: remove, refactor into file. Leaving for backward compat.
  train_model:
    # Fixed parameters
    batch_size: 64
    n_epochs: 1 # Note: epochs per trial
    lr_warmup_iters:  10
    lr_warmdown_ratio: 0.65
    # Optimized learning parameters
    lr: [0.05, 0.3]
    lr_final_frac: [0.01, 0.1]
    weight_decay: [0.01, 0.1]
    clip_grad_norm: [0.5, 1.5]

# TODO: remove, refactor into file. Leaving for backward compat.
# Model Hyperparameters
# Can be tuned, but here will be explored as a grid for comparisons
models:
  base_transformer:
    n_embed: [8, 16, 32, 64, 128]
    n_heads: [1, 2, 4, 8, 16]
    n_layers: [1, 2, 4, 8, 12]
  energy_transformer:
    n_embed: [8, 16, 32, 64, 128]
    n_heads: [1, 2, 4, 8, 16]
    n_layers: [1, 2, 4, 8, 12]