## * Modified version of the original `wandb_config.yaml` file with no model 
## * parameters. Used for the experiment where different model sizes are
## * trained.

# ============================== General Configs ============================= #
method: random
metric: 
  name: train_loss
  goal: minimize
early_terminate:
  type: hyperband
  min_iter: 5
  max_iter: 30
  eta: 3

# ================================ Parameters ================================ #
parameters:
# ------------------------- Training Hyperparameters ------------------------- #
  batch_size:
    # Value = 0 → Use full training set for batch size
    value: 4096
  n_epochs: 
    value: 30 # Note: epochs per trial
  lr_warmup_iters:  
    value: 5
  lr_warmdown_ratio: 
    value: 0.65
  # ------------------------- Training Hyperparameters ------------------------- #
  lr: 
    distribution: log_uniform_values
    min: 1e-5
    max: 1e-2
  lr_final_frac: 
    distribution: log_uniform_values
    min: 1e-3
    max: 0.1
  weight_decay: 
    distribution: log_uniform_values
    min: 0.01
    max: 0.1
  clip_grad_norm: 
    distribution: uniform
    min: 0.5
    max: 1.5
# --------------------------- Model Hyperparameters -------------------------- #
  n_layers: 
    value: 5
  sequence_len:
    value: 39
  vocab_size:
    value: 17
  n_classes:
    value: 10